import type { AnalysisArtifact, RangeCandidate, SourceArtifact } from "../schema/types.js";
const num=(x:unknown)=>{const n=typeof x==="number"?x:typeof x==="string"&&x.trim()?Number(x):NaN;return Number.isFinite(n)?n:null;};
const pairOf=(s:SourceArtifact):any=>s.source==="dexscreener"?(s.payload as any)?.pair??null:null;
function candidate(kind:"CORE"|"BUFFER",price:number|null,pair:any):RangeCandidate{
  const width=kind==="CORE"?.12:.30; const v=num(pair?.volume?.h24)??num(pair?.volume?.h6)??num(pair?.volume?.h1); const hours=num(pair?.volume?.h24)!==null?24:num(pair?.volume?.h6)!==null?6:num(pair?.volume?.h1)!==null?1:null;
  return {kind,strategy:"LEGACY_SOURCE_PROXY_STATIC",lowerPriceUsd:price===null?null:price*(1-width),upperPriceUsd:price===null?null:price*(1+width),widthPct:width*200,score:price!==null&&v!==null?Math.min(100,Math.round(50+Math.log10(Math.max(1,v))*8-width*30)):null,selected:kind==="CORE",replay:{sampleHours:hours,observedVolumeUsd:v,feeProxyUsd:null,weightedVolumeCapturePct:null,activeTimePct:null,crossingDensity:null,boundarySafetyPct:null,structureFitPct:null},failureState:price===null?"BLOCKED_DATA":"BLOCKED_EVIDENCE"};
}
export function buildAnalysis(address:string,sources:SourceArtifact[],timestamp=new Date().toISOString()):AnalysisArtifact{
  const ready=sources.filter(s=>s.status==="READY"); const primary=ready.find(s=>s.source==="okx")??ready.find(s=>s.source==="uniswap"||s.source==="rpc")??ready.find(s=>s.source==="geckoterminal")??ready.find(s=>s.source==="dexscreener")??null; const pair=ready.map(pairOf).find(Boolean); const price=num(pair?.priceUsd); const candidates=[candidate("CORE",price,pair),candidate("BUFFER",price,pair)]; const selected=price===null?null:candidates[0]; const hardData=price===null?"BLOCKED_DATA":"BLOCKED_EVIDENCE";
  return {schemaVersion:"lp-oracle-v3.3",request:{tokenAddress:address,chain:primary?.chainId??null,pool:primary?.poolAddress??null},timestamp,validation:{input:"VALID_EVM_ADDRESS",sourcesReady:ready.length,evidenceGrade:ready.length?"C":"D"},failureState:hardData,evidence:{primarySource:primary?.source??null,sourceCount:ready.length,notes:["Direct-source path is compatibility fallback only; preferred path consumes lp-truth-v1.","Static ranges are explicitly BLOCKED_EVIDENCE; structure-aware replay requires typed historical truth."]},token:{name:pair?.baseToken?.name??null,symbol:pair?.baseToken?.symbol??null,priceUsd:price,marketCapUsd:num(pair?.marketCap)},sources,search:{engine:"STRUCTURE_AWARE_REPLAY_V2",candidatesEvaluated:0,coreStrategy:null,bufferStrategy:null},candidates,decision:{action:"WAIT",selected:selected?.kind??null,score:selected?.score??null,confidence:selected?.score!==null?.45:null,allocation:{corePct:70,bufferPct:30,rationale:"DEFAULT_70_30_UNLESS_VERIFIED_EVIDENCE_JUSTIFIES_OVERRIDE"},failureState:hardData}};
}
