export type Nullable<T> = T | null;
export type FailureState = "BLOCKED_DATA" | "BLOCKED_EVIDENCE" | "BLOCKED_AUTH" | "BLOCKED_EXECUTION";
export type SourceName = "okx" | "uniswap" | "rpc" | "dexpaprika" | "geckoterminal" | "dexscreener" | "revert" | "vfat";
export type SourceArtifact = { source: SourceName; tier: 1 | 2 | 3 | 4; status: "READY" | "BLOCKED" | "UNAVAILABLE"; fetchedAt: string; chainId: Nullable<string>; tokenAddress: string; poolAddress: Nullable<string>; payload: unknown; failureState: Nullable<FailureState>; error: Nullable<string> };
export type Ohlcv = { timestamp:number; open:number; high:number; low:number; close:number; volumeUsd:number };
export type RangeCandidate = {
  kind: "CORE" | "BUFFER";
  strategy: string;
  lowerPriceUsd: Nullable<number>;
  upperPriceUsd: Nullable<number>;
  widthPct: number;
  score: Nullable<number>;
  selected: boolean;
  replay: {
    sampleHours: Nullable<number>;
    observedVolumeUsd: Nullable<number>;
    feeProxyUsd: Nullable<number>;
    weightedVolumeCapturePct: Nullable<number>;
    activeTimePct: Nullable<number>;
    crossingDensity: Nullable<number>;
    boundarySafetyPct: Nullable<number>;
    structureFitPct: Nullable<number>;
  };
  failureState: Nullable<FailureState>;
};
export type TruthHandoff = {
  schemaVersion: "lp-truth-v1";
  request: { tokenAddress: string };
  timestamp: string;
  selectedPool: { chainId: Nullable<string>; poolAddress: string; priceUsd: Nullable<number>; volume24hUsd: Nullable<number>; liquidityUsd: Nullable<number>; feeTier?: Nullable<number>; poolAgeDays: Nullable<number>; source?: string } | null;
  onchainPool?: { feeTier:number; currentTick:number; activeLiquidityRaw:string; sqrtPriceX96:string; canonical:boolean } | null;
  market: { priceUsd: Nullable<number>; high24hUsd: Nullable<number>; low24hUsd: Nullable<number>; high7dUsd: Nullable<number>; low7dUsd: Nullable<number>; volume5mUsd: Nullable<number>; volume30mUsd: Nullable<number>; volume1hUsd: Nullable<number>; volume24hUsd: Nullable<number>; tvlUsd: Nullable<number>; activeLiquidityUsd: Nullable<number>; feeTier: Nullable<number>; poolAgeDays: Nullable<number>; tick: { current: Nullable<number>; lower: Nullable<number>; upper: Nullable<number> }; holderFlow: unknown };
  poolCandidates: unknown[];
  history: { ohlcv5m?:Ohlcv[]; ohlcv30m?:Ohlcv[]; ohlcv1h?:Ohlcv[]; ohlcv1d?:Ohlcv[] };
  evidence: { grade: "A" | "B" | "C" | "D"; freshnessSeconds: Nullable<number>; conflicts: string[]; wickPenalty: boolean; sources: Array<{source?:string;status?:string}> };
  receipts?: { source?: unknown[]; truth?: unknown[] };
  failureState: Nullable<FailureState>;
};
export type DecisionReceipt = { inputSchemaVersion:"lp-truth-v1"; inputHash:string; createdAt:string; action:"ENTER"|"WAIT"|"HOLD"; selected:Nullable<"CORE"|"BUFFER">; failureState:Nullable<FailureState> };
export type AnalysisArtifact = {
  schemaVersion: "lp-oracle-v3.3";
  request: { tokenAddress: string; chain: Nullable<string>; pool: Nullable<string> };
  timestamp: string;
  validation: { input: "VALID_EVM_ADDRESS"; sourcesReady: number; evidenceGrade: "A" | "B" | "C" | "D" };
  failureState: Nullable<FailureState>;
  evidence: { primarySource: Nullable<SourceName>; sourceCount: number; notes: string[] };
  token: { name: Nullable<string>; symbol: Nullable<string>; priceUsd: Nullable<number>; marketCapUsd: Nullable<number> };
  sources: SourceArtifact[];
  search: { engine:"STRUCTURE_AWARE_REPLAY_V2"; candidatesEvaluated:number; coreStrategy:Nullable<string>; bufferStrategy:Nullable<string> };
  candidates: RangeCandidate[];
  decision: {
    action: "ENTER" | "WAIT" | "HOLD";
    selected: Nullable<"CORE" | "BUFFER">;
    score: Nullable<number>;
    confidence: Nullable<number>;
    allocation: { corePct: number; bufferPct: number; rationale: string };
    failureState: Nullable<FailureState>;
  };
  receipts?: { decision: DecisionReceipt };
  truth?: TruthHandoff;
};
